version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_ldap_platform
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /opt/python_ldap_platform/logs:/logs/
      - /opt/python_ldap_platform/python_ldap_platform:/python_ldap_platform/
      - /opt/python_ldap_platform/config.yml:/config.yml
    environment:
      - TZ=Asia/Shanghai
###### 以下注释项为可选变量
#      - LISTEN_PORT=10086   # 自定义端口
#      - CREATE_USER=1       # 0 不创建管理员用户, 1 创建管理员用户,默认是1
#      - USER=jonnyan404     # 自定义管理员用户名
#      - MM=1                # 自定义管理员密码
###### 如果默认用户密码,以及变量添加用户密码无法登录,请参考:https://www.mrdoc.fun/project-1/doc-242/

